#!/bin/bash -e

# Ensure basic settings are available from the environment.
fatal=0
for var in \
  EKB_DRY_RUN \
  EKB_CODENAME \
  EKB_PROJECT_PREFIX \
  EKB_BASELIB \
  EKB_DATA_DIR \
  EKB_HELPERS_DIR \
  EKB_STAGES_DIR \
  EKB_TARGET_DIR \
  EKB_TMP_DIR \
  EKB_OUT_FILE \
  EKB_COMPRESSION
do
  if [ ! -v $var ]; then
    echo "error: required setting $var not set" >&2
    fatal=1
  fi
done

# Warn for other (non-fatal) missing settings
for var in \
  EKB_USB_LABEL \
  EKB_USB_SIZE \
  EKB_KOLIBRI_VERSION \
  EKB_KOLIBRI_EXPLORE_PLUGIN_VERSION \
  EKB_KOLIBRI_ZIM_PLUGIN_VERSION \
  EKB_KOLIBRI_ENDLESS_KEY_APP_VERSION \
  EKB_KOLIBRI_LAUNCHER_WINDOWS_VERSION \
  EKB_KOLIBRI_CENTRAL_CONTENT_BASE_URL \
  EKB_KOLIBRI_INSTALL_CHANNELS \
  EKB_KOLIBRI_CONTENT_PLACEHOLDERS
do
  if [ ! -v $var ]; then
    echo "warn: missing setting $var" >&2
  fi
done

if [ $fatal -eq 1 ] ; then
  echo "error: one or more required settings missing, exiting" >&2
  exit 1
fi

if [ ${EKB_DRY_RUN} == "true" ] ; then
  echo "Running in dry-run mode, exiting" >&2
  exit 0
fi

# Set -ex here so we don't get all the output from the loops above
set -ex

. ${EKB_BASELIB}

# Run stages
${EKB_STAGES_DIR}/ekb_content
${EKB_STAGES_DIR}/ekb_kolibri
${EKB_STAGES_DIR}/ekb_archive
