#!/bin/bash -ex

. ${EKB_BASELIB}


## Check max sixe
size=$(du --block-size=1 -s "${EKB_TARGET_DIR}")
size=${size%$'\t'*}
if [[ "${EKB_MAX_SIZE}" ]] && (( size > EKB_MAX_SIZE * 1000**3 * 96 / 100 )); then
  echo "ERROR: target size ${size} exceeds 96% of ${EKB_MAX_SIZE} GB" >&2
  return 1
fi


## Archive + checksum
rm -f "${EKB_OUT_FILE}"
ekb_compress_dir "${EKB_TARGET_DIR}" "${EKB_OUT_FILE}"
ekb_checksum "${EKB_OUT_FILE}"
